name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true
    
    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-last-accessed: P1DT12H
        purge-primary-key: never

    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      with:
        endpoint: ${{ vars.ATTIC_ENDPOINT }}
        cache: ${{ vars.ATTIC_CACHE }}
        token: ${{ secrets.ATTIC_TOKEN }}
        skip-push: true
    
    - name: Test
      run: nix build .#test
      
    - name: Build
      run: nix build

    - name: Push Cache
      run: attic push respeak ./result
